### ISSUE TITLE
Generate file size is larger than the one with saved with Excel

### ISSUE THREAD

**Issue by hidekoji** [ropensci/writexl#13]
writexl::write_xlsx seems to generate not optimized xlsx file from size point of view.

For example, it generated 90MB file size xlsx file but if I opened up the file in Excel and resaved the file without changing anything the file size went down to 4MB.

**Comment by jeroen** [comment]
Please provide a reproducible example of the file that you generated.

**Comment by hidekoji** [comment]
```r
airlines <- readr::read_csv(file="https://www.dropbox.com/s/xkznuhtokjmjomh/airline_delay_2016_09.csv?dl=1")
writexl::write_xlsx(airlines, path='~//Downloads/text.xlsx', col_names=TRUE);

```

This generates 39.3MB xlsx file. But if you open it with Excel or Number and re-saved it as Excel without changing anything, the file reduced to 4.7MB

**Comment by jeroen** [comment]
If I open it in excel and then resave it, the size actually increases to 41.4MB. I'm using excel for mac 15.41.

**Comment by nacnudus** [comment]
I also cannot reproduce this problem.  Resaving it in various formats with Excel 2013 for PC (v14.0760):

* xlsx = 41 MB
* xlsb = 18 MB
* csv = 40 MB
* csv zipped = 7.9 MB
* xls = 16 MB (which truncates the data to 65536 rows)

**Comment by hidekoji** [comment]
ok, could you please try this?

1. On Mac, with Numbers open the xlsx file generated with writexl::write_xlsx 
2. Without changing anything, export as Excel.

Then you'll get xlsx file with 4.7MB. Here is the xlsx file.

https://www.dropbox.com/s/pgqf0fzn682g2od/test-reduced.xlsx?dl=0

**Comment by nacnudus** [comment]
@hidekoji This is what happens for me.

1. Download the file from dropbox, which is 4.6 MB.
2. Import it into R with readxl.
3. Write it to a new xlsx file with writexl::write_xlsx, which creates a 5.1 MB file.
4. Open that 5.1 MB file in Excel 2013 for PC and resave it, which creates a 6.0 MB file.

Are you using the lateset version of `writexl`?

**Comment by Giaino78** [comment]
Finally, no answer to this question? I have the same issue. I download a .xlsx file, size 500KB, after opening and saving it without any changes the size increase at 1400KB.
What can I do?

**Comment by jmcnamara** [comment]
I think this issue should be closed. 

The underlying libxlsxwriter library specifically aims to produce xlsx file that are the same as the files produced by Excel. There may be differences in overall size caused by the zip library and compression level but these shouldn't be anything other than +/- 10%. Also, the same mechanism is used in the libxlsxwriter sister libraries of XlsxWriter in Python and Excel::Writer::XLSX in Perl and this issue is never reported there.

Finally, I tried to reproduce with the the file provided by @hidekoji above and cannot:

```
4.5M  test-reduced.xlsx    # Original
6.3M  test-reduced2.xlsx   # Resaved in Excel 2011
4.5M  test-reduced3.xlsx   # Opened in Numbers and reserved as an xlsx file
```

Other people in the thread have also pointed out that they cannot reproduce this so I think it should be closed.
