### ISSUE TITLE
Please remove "clippy"

### ISSUE THREAD

**Issue by njbart** [ropensci/writexl#39]
This is extremely annoying, and ["limiting"](https://github.com/ropensci/writexl/issues/12) the discussion is not in the least bit helpful.

Just get rid of it!

**Comment by KyleHaynes** [comment]
How is it limiting?

**Comment by p-phillips** [comment]
> How is it limiting?
Because the original issue complaining about clippy was then set to only allow contributors to comment.

I agree  that clippy is a PITA.  I also spent some time trying to find out if I had an infected version of rstudio (and for a short while wondered if my workstation had been compromised when the damn paperclip started dancing over the man page) before I realised this was intended by the author of writexl.  

writexl is excellent - clippy is a distraction I'm afraid.

**Comment by KyleHaynes** [comment]
Apologies ... scrap my comment, I misread it.

If users have such a gripe with it, perhaps take it up with CRAN regarding why they allow JS/CSS code to be added to HTML help docs, especially when it's externally sourced - potential security implications?

**Comment by zeehio** [comment]
> Apologies ... scrap my comment, I misread it.
> 
> If users have such a gripe with it, perhaps take it up with CRAN regarding why they allow JS/CSS code to be added to HTML help docs, especially when it's externally sourced - potential security implications?

I have not seen complaints about general use of JS/CSS in this thread. Just about Clippy. Clippy behaves like those pop-up advertisements that do not offer an easy way to close them. So far no other CRAN package I've seen abuses JS/CSS in the documentation pages in this way. Wasting CRAN maintainers time in writing policy because this package abuses JS/CSS to play a joke on the user should not be the solution.

It's fine to make clippy pop up and play the joke on the user when we all laugh. I did laugh. It is not fine when the user does not find it funny anymore and he/she does not have an obvious way to disable it. It disrupts the user's attention.

Since this is free software, ropensci is free to not let us choose to disable clippy. But since this is free software, I can maintain my own fork of `writexl` that tracks writexl releases disabling the "feature" I don't like (I would happily include a close button, because I do find clippy funny sometimes, but I don't have the time to do that now so I'm just disabling it).

    remotes::install_github("zeehio/writexl@v1.1-noclippy")

What a waste of time for everyone.

writexl is a great package (besides this), and I am very grateful to the developers for maintaining it.

**Comment by yaakovfeldman** [comment]
I think it's a great Easter egg. These are always controversial but have come into fashion at even some very large organisations. My only complaint is that it doesn't render correctly when a dark theme with light text is used in RStudio.

**Comment by datatoolbox** [comment]
Hi Kyle.  You asked above how Clippy is limiting.  I think it is limiting in two ways.  First, it covers useful information, and it follows the cursor in an odd way.  This mostly just a bit of an inconvenience.  But the second way is because it is such an odd occurrence that, like others have expressed, I thought there was something wrong with my MS install or my OS.  I spent well over half an hour looking for MS and OS threads about recent problems with Clippy appearing.  I eventually gave up searching.  But the next two times I got help on writexl I spent almost as much time - frustrated that someone hadn't fixed the MS or OS bug yet, or thinking that maybe I just needed to update my MS software or my OS.  The fact that it is so non-standard that it causes this kind of confusion.  Now that I know it is intentional, I will just ignore it and move on.  But I care about all the people who haven't found this out and waste their time thinking there is a bug somewhere, trying to figure out how to update their system.  It is a bit humorous, but it is also causing a lot of people to spend time trying to figure out what the problem is on their system.  Thanks for reading.
